### PR TITLE
Feature/cd 126 apply service worker merge

### PR DESCRIPTION
**Pull request by duc-q**
### Summary
Move User logic into Class, including:
- Creating new User
- Welcome back returning User
- Sign deploy for Private key

### Checklist:

-   [X] I removed all commented or unnecessary code.
-   [X] My code has covered these test cases (please list down your tested cases)

### CODE REVIEW

**Comment by duc-q** [comment]
@gaupoit  @djhahe 

Please do review and merge from `https://github.com/CasperDash/casperdash-client/pull/129` first before merging this PR

**Comment by gaupoit** [comment]
hi a @duc-q , just kindly remind to list down the tested cases and proof (picture) under checklist `My code has covered these test cases (please list down your tested cases)`

**Comment by gaupoit** [comment]
Screen Shot 2022-09-05 at 11 40 56

hi a @duc-q , I cannot create password "T@@@olao12345"

**Comment by ducquach-groove** [comment]
> hi a @duc-q , just kindly remind to list down the tested cases and proof (picture) under checklist `My code has covered these test cases (please list down your tested cases)`

Thanks for noticing, Please use this branch (already merged into this PR) for new UTs:
https://github.com/CasperDash/casperdash-client/pull/129

**Comment by djhahe** [comment]
> Screen Shot 2022-09-05 at 11 40 56
> 
> hi a @duc-q , I cannot create password "T@@@olao12345"

 @gaupoit I can create account with above password normally. Pls check again

**Comment by gaupoit** [comment]
hi @duc-q , @djhahe , please double check this error while running command `yarn build-extension-testnet` 

```
10% building 0/2 entries 29/64 dependencies 0/27 modules[BABEL] Note: The code generator has deoptimised the styling of /Users/gaupoit/Work/casperdash/casperdash-client/client/node_modules/casper-js-sdk/dist/lib.js as it exceeds the max of 500KB.
[webpack-cli] HookWebpackError: Transform failed with 100 errors:
static/js/sw/service-worker.5eb6ce94.js:16:0: ERROR: Transforming const to the configured target environment ("es5") is not supported yet
static/js/sw/service-worker.5eb6ce94.js:17:0: ERROR: Transforming class syntax to the configured target environment ("es5") is not supported yet
static/js/sw/service-worker.5eb6ce94.js:18:13: ERROR: Transforming object literal extensions to the configured target environment ("es5") is not supported yet
static/js/sw/service-worker.5eb6ce94.js:27:11: ERROR: Transforming object literal extensions to the configured target environment ("es5") is not supported yet
static/js/sw/service-worker.5eb6ce94.js:29:6: ERROR: Transforming let to the configured target environment ("es5") is not supported yet
...
    at makeWebpackError (/Users/gaupoit/Work/casperdash/casperdash-client/client/node_modules/webpack/lib/HookWebpackError.js:48:9)
    at /Users/gaupoit/Work/casperdash/casperdash-client/client/node_modules/webpack/lib/Compilation.js:3055:12
    at eval (eval at create (/Users/gaupoit/Work/casperdash/casperdash-client/client/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:68:1)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
-- inner error --
Error: Transform failed with 100 errors:
static/js/sw/service-worker.5eb6ce94.js:16:0: ERROR: Transforming const to the configured target environment ("es5") is not supported yet
static/js/sw/service-worker.5eb6ce94.js:17:0: ERROR: Transforming class syntax to the configured target environment ("es5") is not supported yet
static/js/sw/service-worker.5eb6ce94.js:18:13: ERROR: Transforming object literal extensions to the configured target environment ("es5") is not supported yet
static/js/sw/service-worker.5eb6ce94.js:27:11: ERROR: Transforming object literal extensions to the configured target environment ("es5") is not supported yet
static/js/sw/service-worker.5eb6ce94.js:29:6: ERROR: Transforming let to the configured target environment ("es5") is not supported yet
...
    at failureErrorWithLog (/Users/gaupoit/Work/casperdash/casperdash-client/client/node_modules/esbuild/lib/main.js:1503:15)
    at /Users/gaupoit/Work/casperdash/casperdash-client/client/node_modules/esbuild/lib/main.js:1292:29
    at /Users/gaupoit/Work/casperdash/casperdash-client/client/node_modules/esbuild/lib/main.js:634:9
    at handleIncomingPacket (/Users/gaupoit/Work/casperdash/casperdash-client/client/node_modules/esbuild/lib/main.js:731:9)
    at Socket.readFromStdout (/Users/gaupoit/Work/casperdash/casperdash-client/client/node_modules/esbuild/lib/main.js:601:7)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:199:23)
caused by plugins in Compilation.hooks.processAssets
Error: Transform failed with 100 errors:
static/js/sw/service-worker.5eb6ce94.js:16:0: ERROR: Transforming const to the configured target environment ("es5") is not supported yet
static/js/sw/service-worker.5eb6ce94.js:17:0: ERROR: Transforming class syntax to the configured target environment ("es5") is not supported yet
static/js/sw/service-worker.5eb6ce94.js:18:13: ERROR: Transforming object literal extensions to the configured target environment ("es5") is not supported yet
static/js/sw/service-worker.5eb6ce94.js:27:11: ERROR: Transforming object literal extensions to the configured target environment ("es5") is not supported yet
static/js/sw/service-worker.5eb6ce94.js:29:6: ERROR: Transforming let to the configured target environment ("es5") is not supported yet
...
    at failureErrorWithLog (/Users/gaupoit/Work/casperdash/casperdash-client/client/node_modules/esbuild/lib/main.js:1503:15)
    at /Users/gaupoit/Work/casperdash/casperdash-client/client/node_modules/esbuild/lib/main.js:1292:29
    at /Users/gaupoit/Work/casperdash/casperdash-client/client/node_modules/esbuild/lib/main.js:634:9
    at handleIncomingPacket (/Users/gaupoit/Work/casperdash/casperdash-client/client/node_modules/esbuild/lib/main.js:731:9)
    at Socket.readFromStdout (/Users/gaupoit/Work/casperdash/casperdash-client/client/node_modules/esbuild/lib/main.js:601:7)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:199:23)
error Command failed with exit code 2.
```

**Comment by duc-q** [comment]
> hi @duc-q , @djhahe , please double check this error while running command `yarn build-extension-testnet`
> 
> ```
> 10% building 0/2 entries 29/64 dependencies 0/27 modules[BABEL] Note: The code generator has deoptimised the styling of /Users/gaupoit/Work/casperdash/casperdash-client/client/node_modules/casper-js-sdk/dist/lib.js as it exceeds the max of 500KB.
> [webpack-cli] HookWebpackError: Transform failed with 100 errors:
> static/js/sw/service-worker.5eb6ce94.js:16:0: ERROR: Transforming const to the configured target environment ("es5") is not supported yet
> static/js/sw/service-worker.5eb6ce94.js:17:0: ERROR: Transforming class syntax to the configured target environment ("es5") is not supported yet
> static/js/sw/service-worker.5eb6ce94.js:18:13: ERROR: Transforming object literal extensions to the configured target environment ("es5") is not supported yet
> static/js/sw/service-worker.5eb6ce94.js:27:11: ERROR: Transforming object literal extensions to the configured target environment ("es5") is not supported yet
> static/js/sw/service-worker.5eb6ce94.js:29:6: ERROR: Transforming let to the configured target environment ("es5") is not supported yet
> ...
>     at makeWebpackError (/Users/gaupoit/Work/casperdash/casperdash-client/client/node_modules/webpack/lib/HookWebpackError.js:48:9)
>     at /Users/gaupoit/Work/casperdash/casperdash-client/client/node_modules/webpack/lib/Compilation.js:3055:12
>     at eval (eval at create (/Users/gaupoit/Work/casperdash/casperdash-client/client/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:68:1)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
> -- inner error --
> Error: Transform failed with 100 errors:
> static/js/sw/service-worker.5eb6ce94.js:16:0: ERROR: Transforming const to the configured target environment ("es5") is not supported yet
> static/js/sw/service-worker.5eb6ce94.js:17:0: ERROR: Transforming class syntax to the configured target environment ("es5") is not supported yet
> static/js/sw/service-worker.5eb6ce94.js:18:13: ERROR: Transforming object literal extensions to the configured target environment ("es5") is not supported yet
> static/js/sw/service-worker.5eb6ce94.js:27:11: ERROR: Transforming object literal extensions to the configured target environment ("es5") is not supported yet
> static/js/sw/service-worker.5eb6ce94.js:29:6: ERROR: Transforming let to the configured target environment ("es5") is not supported yet
> ...
>     at failureErrorWithLog (/Users/gaupoit/Work/casperdash/casperdash-client/client/node_modules/esbuild/lib/main.js:1503:15)
>     at /Users/gaupoit/Work/casperdash/casperdash-client/client/node_modules/esbuild/lib/main.js:1292:29
>     at /Users/gaupoit/Work/casperdash/casperdash-client/client/node_modules/esbuild/lib/main.js:634:9
>     at handleIncomingPacket (/Users/gaupoit/Work/casperdash/casperdash-client/client/node_modules/esbuild/lib/main.js:731:9)
>     at Socket.readFromStdout (/Users/gaupoit/Work/casperdash/casperdash-client/client/node_modules/esbuild/lib/main.js:601:7)
>     at Socket.emit (node:events:390:28)
>     at addChunk (node:internal/streams/readable:315:12)
>     at readableAddChunk (node:internal/streams/readable:289:9)
>     at Socket.Readable.push (node:internal/streams/readable:228:10)
>     at Pipe.onStreamRead (node:internal/stream_base_commons:199:23)
> caused by plugins in Compilation.hooks.processAssets
> Error: Transform failed with 100 errors:
> static/js/sw/service-worker.5eb6ce94.js:16:0: ERROR: Transforming const to the configured target environment ("es5") is not supported yet
> static/js/sw/service-worker.5eb6ce94.js:17:0: ERROR: Transforming class syntax to the configured target environment ("es5") is not supported yet
> static/js/sw/service-worker.5eb6ce94.js:18:13: ERROR: Transforming object literal extensions to the configured target environment ("es5") is not supported yet
> static/js/sw/service-worker.5eb6ce94.js:27:11: ERROR: Transforming object literal extensions to the configured target environment ("es5") is not supported yet
> static/js/sw/service-worker.5eb6ce94.js:29:6: ERROR: Transforming let to the configured target environment ("es5") is not supported yet
> ...
>     at failureErrorWithLog (/Users/gaupoit/Work/casperdash/casperdash-client/client/node_modules/esbuild/lib/main.js:1503:15)
>     at /Users/gaupoit/Work/casperdash/casperdash-client/client/node_modules/esbuild/lib/main.js:1292:29
>     at /Users/gaupoit/Work/casperdash/casperdash-client/client/node_modules/esbuild/lib/main.js:634:9
>     at handleIncomingPacket (/Users/gaupoit/Work/casperdash/casperdash-client/client/node_modules/esbuild/lib/main.js:731:9)
>     at Socket.readFromStdout (/Users/gaupoit/Work/casperdash/casperdash-client/client/node_modules/esbuild/lib/main.js:601:7)
>     at Socket.emit (node:events:390:28)
>     at addChunk (node:internal/streams/readable:315:12)
>     at readableAddChunk (node:internal/streams/readable:289:9)
>     at Socket.Readable.push (node:internal/streams/readable:228:10)
>     at Pipe.onStreamRead (node:internal/stream_base_commons:199:23)
> error Command failed with exit code 2.
> ```

@gaupoit  @djhahe 

In one of our recent changes related to service-worker bundling, I notice we're adding this `es5` target:
image

I've tried to comment out this very line and rerun  `yarn build-extension-testnet` and it works.

@djhahe  Can you help to clarify with us why we need this? I did a bit googling and default is `es2015`

Link ref: https://github.com/privatenumber/esbuild-loader

Thanks,

**Comment by duc-q** [comment]
@djhahe @gaupoit @hoailinh1210

Just a friendly reminder, at this phase we should use this branch CD-126-apply-service-worker-MERGE as our primary release for this milestone.

When all the stories are finished, we then can merge this CD-126/MERGE into dev branch as usual.

Let me know if this is okay to you guys,

Thanks,

👍

**Comment by gaupoit** [comment]
> @djhahe @gaupoit @hoailinh1210
> 
> Just a friendly reminder, at this phase we should use this branch CD-126-apply-service-worker-MERGE as our primary release for this milestone.
> 
> When all the stories are finished, we then can merge this CD-126/MERGE into dev branch as usual.
> 
> Let me know if this is okay to you guys,
> 
> Thanks,
> 
> 👍

I think we can merge this branch into develop after resolving this issue: https://github.com/CasperDash/casperdash-client/pull/128#issuecomment-1237853908.

We can log any related issues later.

**Comment by gaupoit** [comment]
Tested cases:

- [x] Create new wallet
- [x] Send CSPR
- [x] Delegate
- [x] Un-delegate
- [x] Import recovery phase 

We can merge this PR then.

P/s Waiting for these tickets https://github.com/CasperDash/casperdash-client/issues/135 and #136 which helps the testing process easier and better UX.

**Pull request merged**
