### PR TITLE
Feature/create wallet

### PR DESCRIPTION
**Pull request by duc-q**
### Summary
Implement Create Wallet module, and add Welcome Screen so User can login back.

### Checklist

-   [X] I removed all commented or unnecessary code.
-   [X] Provide the screenshots due to UI changed or bug fixed
-   [X] My code has covered these test cases (please list down your tested cases):
  - Update unit test for Create Wallet actions
  - Update unit test for Create Wallet selectors
  - Update unit test for custom hook useCreateUser

New UI screenshots:
Create new wallet
image
Keyphrase list screen
image
Double check words screen
image
Password entering screen
image
Welcome Back screen
image

More unit tests coming soon

### CODE REVIEW

**Comment by gaupoit** [comment]
```
Uncaught TypeError: Cannot destructure property 'publicKey' of 'cacheConnectedAccount' as it is undefined.
    at WithAccount (WithAccount.jsx:9:22)
    at renderWithHooks (react-dom.development.js:14985:18)
    at mountIndeterminateComponent (react-dom.development.js:17811:13)
    at beginWork (react-dom.development.js:19049:16)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:16)
    at invokeGuardedCallback (react-dom.development.js:4056:31)
    at beginWork$1 (react-dom.development.js:23964:7)
    at performUnitOfWork (react-dom.development.js:22779:12)
    at workLoopSync (react-dom.development.js:22707:5)
```


hi @duc-q , I met this error when loading unpack extension form this branch. Steps to reproduce:

1. Run `yarn dev-extension-testnet` 
1. Load the unpack extension in client/build_extension folder
1. Disable the production extension
1. Enable the development extension

**Comment by duc-q** [comment]
> ```
> Uncaught TypeError: Cannot destructure property 'publicKey' of 'cacheConnectedAccount' as it is undefined.
>     at WithAccount (WithAccount.jsx:9:22)
>     at renderWithHooks (react-dom.development.js:14985:18)
>     at mountIndeterminateComponent (react-dom.development.js:17811:13)
>     at beginWork (react-dom.development.js:19049:16)
>     at HTMLUnknownElement.callCallback (react-dom.development.js:3945:14)
>     at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:16)
>     at invokeGuardedCallback (react-dom.development.js:4056:31)
>     at beginWork$1 (react-dom.development.js:23964:7)
>     at performUnitOfWork (react-dom.development.js:22779:12)
>     at workLoopSync (react-dom.development.js:22707:5)
> ```
> 
> hi @duc-q , I met this error when loading unpack extension form this branch. Steps to reproduce:
> 
> 1. Run `yarn dev-extension-testnet`
> 2. Load the unpack extension in client/build_extension folder
> 3. Disable the production extension
> 4. Enable the development extension

@gaupoit 

Please pull the latest source and rerun again, I've resolved the above Bug.

**Comment by gaupoit** [comment]
> > ```
> > Uncaught TypeError: Cannot destructure property 'publicKey' of 'cacheConnectedAccount' as it is undefined.
> >     at WithAccount (WithAccount.jsx:9:22)
> >     at renderWithHooks (react-dom.development.js:14985:18)
> >     at mountIndeterminateComponent (react-dom.development.js:17811:13)
> >     at beginWork (react-dom.development.js:19049:16)
> >     at HTMLUnknownElement.callCallback (react-dom.development.js:3945:14)
> >     at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:16)
> >     at invokeGuardedCallback (react-dom.development.js:4056:31)
> >     at beginWork$1 (react-dom.development.js:23964:7)
> >     at performUnitOfWork (react-dom.development.js:22779:12)
> >     at workLoopSync (react-dom.development.js:22707:5)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > hi @duc-q , I met this error when loading unpack extension form this branch. Steps to reproduce:
> > 
> > 1. Run `yarn dev-extension-testnet`
> > 2. Load the unpack extension in client/build_extension folder
> > 3. Disable the production extension
> > 4. Enable the development extension
> 
> @gaupoit
> 
> Please pull the latest source and rerun again, I've resolved the above Bug.

Many thanks, it has been fixed in [174df2d](https://github.com/CasperDash/casperdash-client/pull/105/commits/174df2dc613d8d5956ab000826899050793906b0)

**Comment by gaupoit** [comment]
hi @duc-q @djhahe , please double check the new created public key. It seems to be invalid public key.

- This is my new created public key: 00d18bee34207b6d2ae7789dd5824f0b506a678ec5889bbcadd661911da282b31c
- Tested on https://testnet.casperdash.io/dashboard

Screen Shot 2022-08-02 at 17 17 59

**Comment by djhahe** [comment]
hi a @duc-q 
Verify screen always checks top 4 words? pls help to check
image

**Comment by djhahe** [comment]
> hi @duc-q @djhahe , please double check the new created public key. It seems to be invalid public key.
> 
> * This is my new created public key: 00d18bee34207b6d2ae7789dd5824f0b506a678ec5889bbcadd661911da282b31c
> * Tested on https://testnet.casperdash.io/dashboard
> 
> Screen Shot 2022-08-02 at 17 17 59

we should use `getPublicAddress()` instead of `getPublicKey()`. @duc-q  please help to update the function

**Comment by duc-q** [comment]
> hi a @duc-q Verify screen always checks top 4 words? pls help to check image

Bug resolved, created PR and merged: https://github.com/CasperDash/casperdash-client/pull/106

**Comment by duc-q** [comment]
> > hi @duc-q @djhahe , please double check the new created public key. It seems to be invalid public key.
> > 
> > * This is my new created public key: 00d18bee34207b6d2ae7789dd5824f0b506a678ec5889bbcadd661911da282b31c
> > * Tested on https://testnet.casperdash.io/dashboard
> > 
> > Screen Shot 2022-08-02 at 17 17 59
> 
> we should use `getPublicAddress()` instead of `getPublicKey()`. @duc-q please help to update the function

@gaupoit  @djhahe  Please review and check this PR: https://github.com/CasperDash/casperdash-client/pull/107

Thanks,

**Review by djhahe — APPROVED** [review]
LGTM

**Pull request merged**
