### PR TITLE
Fix: #161 Delete all data button is not correct style

### PR DESCRIPTION
**Pull request by hoailinh1210**
### Summary (Please recap what you changed or fixed)

image

### Checklist (If you won't pass this checklist please comment why)

-   [x] I removed all commented or unnecessary code.
-   [x] Provide the screenshots due to UI changed or bug fixed
-   [x] My code has covered these test cases (please list down your tested cases):

### CODE REVIEW

**Comment by gaupoit** [comment]
hi @hoailinh1210 , plz have a look the UT has been failed.

**Review by duc-q — COMMENTED** [review]
@hoailinh1210 
Please pull latest source to your branch. I've updated some changes, this includes:
- Clean up unused code
- Change correct function names for Locking and Delete. Prior to this change, they were in reverse mode. (See https://github.com/CasperDash/casperdash-client/pull/167/commits/d92da3c2a238721312a25a075007d19e71e2c088)
- Update ConfirmModal to default export, also change prop name from `onOK` to `onConfirm`. (See https://github.com/CasperDash/casperdash-client/pull/167/commits/93d313f0b9af88172e9b4c91451a49966e4b0c23)
- Update text warning for better reading.
- Update minor styles issues related to buttons.

Please test around or update missing UT if you miss it. Otherwise this looks good to me.

Cheers

**Comment by duc-q** [comment]
@hoailinh1210 

Please help to fix up issues related to ESLint:

image

Thanks,

**Comment by hoailinh1210** [comment]
> @hoailinh1210
> 
> Please help to fix up issues related to ESLint:
> 
> image
> 
> Thanks,

Hello @duc-q bro,
I refactored the coding style with Eslint, please take a look on d43ee1b39ea0471fdb470623ef2237db2cea1b05

**Comment by gaupoit** [comment]
hi a @duc-q plz help to review it. Cheers.

**Review by duc-q — APPROVED** [review]
LGTM

**Pull request merged**
